CREATE TABLE seedler_info (
        id int,
        name VARCHAR(50) NOT NULL,
        role ENUM('DEVOPS_ENGINEER', 'FRONTEND_DEVELOPER', 'BACKEND_DEVELOPER', 'UI_UX_DESIGNER', 'DATA_ENGINEER') NOT NULL,
        seedler_group ENUM('PLATFORM', 'PROCESS_INTELLIGENCE','BMW', 'RESEARCH_AND_PI_SOLUTIONS', 'PROCESS_INSIGHTS') NOT NULL,
        team ENUM('LAKE_KRAKEN', 'LEGO_KRAKEN', 'OTTO_KRAKEN', 'WILD_KRAKEN', 'MOTHER_OF_KRAKEN', 'THE_AVENGERS',
            'CONNECTORS', 'SIMS', 'WOLF_PACK', 'TEAM_JOURNEY_MODELLING', 'HUBBITS', 'GRIZZLES', 'PUZZLES', 'AREA_23',
            'DATA_INSIGHT', 'RAVEN', 'SOLUTIONS', 'MOVE_THE_NEEDLE', 'USER_PRODUCT_INSIGHTS', 'VALUE_ACCELERATOR') NOT NULL,
        location varchar(20) NOT NULL,
        bio text NOT NULL,
        PRIMARY KEY (id));

insert into seedler_info values (1, "Lido Mazzucco", "BACKEND_DEVELOPER", "PLATFORM", "PUZZLES", "Berlin", "Hi, I'm Lido.");
