use seedler;

CREATE TABLE IF NOT EXISTS seedler_info (
        id int,
        name VARCHAR(50) NOT NULL,
        role ENUM('DEVOPS_ENGINEER', 'FRONTEND_DEVELOPER', 'BACKEND_DEVELOPER', 'UI_UX_DESIGNER', 'DATA_ENGINEER') NOT NULL,
        seedler_group ENUM('PROCESS_PLATFORM', 'PROCESS_INTELLIGENCE','BMW', 'RESEARCH_AND_PI_SOLUTIONS', 'PROCESS_INSIGHTS') NOT NULL,
        team ENUM('LAKE_KRAKEN', 'LEGO_KRAKEN', 'OTTO_KRAKEN', 'WILD_KRAKEN', 'MOTHER_OF_KRAKENS', 'AVENGERS', 'CONNECTORS', 'SIMS',
            'WOLF_PACK', 'JOURNEY_MAPPING', 'REPOSITORY', 'HUBBITS_FE', 'COLLABORATORS', 'GRIZZLY_PACK', 'PUZZLE', 'AREA_23',
            'DATA_INSIGHTS', 'RAVEN', 'VALUE_ACCELERATOR', 'SOLUTIONS', 'MOVE_THE_NEEDLE', 'USER_AND_PRODUCT_INSIGHTS') NOT NULL,
        location varchar(20) NOT NULL,
        bio text NOT NULL,
        PRIMARY KEY (id));

insert into seedler_info values (1, "Lido Mazzucco", "BACKEND_DEVELOPER", "PLATFORM", "PUZZLE", "Berlin", "Hi, I'm Lido.");
