package com.sunrise.seedling.model;

public enum Team {

    LAKE_KRAKEN, LEGO_KRAKEN, OTTO_KRAKEN, WILD_KRAKEN, MOTHER_OF_KRAKENS, AVENGERS, CONNECTORS, SIMS,
    WOLF_PACK, JOURNEY_MAPPING, REPOSITORY, HUBBITS_FE, COLLABORATORS, GRIZZLY_PACK, PUZZLE, AREA_23, DATA_INSIGHTS, RAVEN,VALUE_ACCELERATOR, SOLUTIONS,
    MOVE_THE_NEEDLE, USER_AND_PRODUCT_INSIGHTS
}
