package com.sunrise.seedling.model;

public enum Team {

    LAKE_KRAKEN, LEGO_KRAKEN, OTTO_KRAKEN, WILD_KRAKEN, MOTHER_OF_KRAKEN, THE_AVENGERS, CONNECTORS, SIMS,
    WOLF_PACK, TEAM_JOURNEY_MODELLING, HUBBITS, GRIZZLES, PUZZLES, AREA_23, DATA_INSIGHT, RAVEN, SOLUTIONS,
    MOVE_THE_NEEDLE, USER_PRODUCT_INSIGHTS, VALUE_ACCELERATOR
}
